name: Feature Template2
description: κ°λ° κµ¬ν„ ν…ν”λ¦Ώμ…λ‹λ‹¤.
title: "[Feature] "
labels: ["π Feature"]
assignees: ["330sum", "lkdcode"]
body:
  - type: markdown
    attributes:
      value: |
        π’΅μ–΄λ–¤ κΈ°λ¥μΈκ°€μ”?
        > μ¶”κ°€ν•λ ¤λ” κΈ°λ¥μ— λ€ν•΄ κ°„κ²°ν•κ² μ„¤λ…ν•΄μ£Όμ„Έμ”

  - type: markdown
    attributes:
      value: |
        ### β¨μ‘μ—… μƒμ„Έ λ‚΄μ©
        μ•„λμ μ²΄ν¬λ¦¬μ¤νΈλ¥Ό ν™•μΈν•΄ μ£Όμ„Έμ”:

        - [ ] TO DO
        - [ ] TO DO
        - [ ] TO DO