name: ✅ Test Template
description: 새로운 테스트 케이스를 작성할 때 이 템플릿을 사용하세요.
title: "[Test] "
labels: ["✅ Test"]
body:
  - type: input
    id: text1
    attributes:
      label: ⭐️ 테스트 설명
      description: 어떤 테스트인지 자세한 설명을 제공하세요.
      placeholder: 테스트 설명
    validations:
      required: true

  - type: textarea
    id: text2
    attributes:
      label: 📋 체크 리스트
      description: 테스트에 대한 계획을 작성해 주세요.
      placeholder: 테스트 계획 작성 (제한 없음!)
      value: |
        > - [ ] 🧪
        > - [ ] 🧪
        > - [ ] 🧪
        > - [ ] 🧪
        > - [ ] 🧪
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Test 이슈 발행 체크리스트
        아래의 체크리스트를 확인해 주세요!

        - [x] 중복된 테스트가 있나요?
        - [x] Given-When-Then 의 형식을 따르도록 진행했나요?
        - [x] 테스트와 동시에 리팩터링도 시도하셨나요?
        - [x] 견고한 소프트웨어 구축에 한 걸음 다가가셨나요?