name: Auto-add to project

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-add to project
        uses: actions/add-to-project@v1
        with:
          # repo-token: ${{ secrets.GITHUB_TOKEN }}
          project-url: 'https://github.com/orgs/sonkkot/projects/3'
          column-name: 'To Do'
